language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: 07oh+7g13BUhzdOJkJ6STR3LOuXo+S22k21EKfIJX7Xrslqog8vlh/sOrbwatFyT+g9T5UCOkH5lVJI0kLy0ln6NDeoJTDVlB1/FdSMmbddjt+3kVMVQAXw02joGQVNOofobwTXdq6N9M8N6R0lD19ZPCVuvX6BUsV4XUxeVv+xB3Z0n30T9pp6/rVIE0wtji6GGKPZGtzwhtA9JVaA0GV5qJCbtr6kfQMmqOWUJ0iuo9TBqiSND6l21RvwD4f+B5eRhNESVwI0XCeDQqibojbOgaxZyztDGWOCUSMzwpnj0QV3hrz0mVL0HWFeyY+mzLihMruhN9TyB8qNaTuZNtRZsO4RN4THelDZwjPocRYtJFmJmm6okkQNxGD8VCgU0oICy72hHpR2A7GmuCLPlEfiAzUT1m0MfYfKJvs/7qw1ONhVCd6FxYujOqQq7AL0GOUf5mrbaEK06uGPKpUvh50se5OiVuWnGsVG7sp6bqJfARL1M5rQNOtl9izg298MYEiFp6plH+wiMAyXI8U2XcTxALoEDMa64+hWi2yhwOMkW3X7PcnMRSt0J4ILsz/0N9xA2drrmU/NZFuUnHvNzAcsS2537slLeg0mruIOB9x7I/tOImWgoavRwJGgbXJO6q3+UZuPSloAxxLvVnZAyZPuTIO8FCiPY12kHRPYHQ/k=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
