language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: oKVLlX/5eIXWjfe8k+lD5xqZyclWIKWlU9Sy70UOX4doD6asRNzYdja5WcziUX9oC72ohGw9N91rUKKEL47fOuF476FEcl5AUkLYTItupefd2TXASSGJLnfqpqFuuG3Wqar5oP+0MNETLt/G7kRHLIVGCz00HWiymQr2eUSlzrawGEuYHl4I2S6H1Jg8K9durLqGpPFqUEgeSDOwuPebjisESK+D3pG/yK8topQ2y4jPGBiDF1LNl8hYsx4+rR24wUrWhea1apwPxAimy1EMVcdS1BAbXs7oomCmw+RcoWH6QCrBQPdzu+/rS3WSiBOxvl6se84P33z7mzI2FcxY3YmMT+W05GpxdZP9xxb1eht4CdOPeVxWAEqnRcjWteOpDnGEKeVsqaZMSyTtF61R+5Anr2emQ1tZH2etfPqW4v9Q/EzoaEBpmZBNH+nwIgl7wumQ37SEWP7GnQA9VgbP7ydXAl1POVR75i3fRrlQPJoEnWchh9Q9hZfBahqXiC8aUmy9mFUajzPa1iJ3fNKjYzvzGyjcbk0mPTwtnBljauX3g0xdu6ISzXNdHfnS/HS0mPD5I45iJjHkAD7RDADZq1MHPnk8HV3G2V29C6FV+zgziGLOaqRZl6sw27fBLeh9Gc5ltI663+4k9c/XGeSt0fZ9u/OdplWa+SGOYwDP5+M=
jdk:
- openjdk11
sudo: true
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
